quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
#quarkus.datasource.password=josueNSD6
quarkus.datasource.password=labcom,2015
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/book_pd

quarkus.http.port=8080


quarkus.stork.authors-api.service-discovery.type=static
quarkus.stork.authors-api.service-discovery.address-list=localhost:8070,localhost:8071
quarkus.stork.authors-api.load-balancer.type=round-robin