quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=josueNSD6
#quarkus.datasource.password=labcom,2015
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/book_pd

quarkus.http.port=8070
quarkus.http.host=0.0.0.0

consul.host=127.0.0.1
consul.port=8500